### ISSUE TITLE
请问模型可以做图像的outpainting吗？效果如何？

### ISSUE THREAD

**Issue by ustczhouyu** [mayuelala/FollowYourCanvas#1]
请问模型可以做图像的outpainting吗？效果如何？

**Comment by mayuelala** [comment]
感谢关注，是可以的，图像的outpainting可以当做是单帧的video进行操作

**Comment by ustczhouyu** [comment]
好的，效果跟目前的图像outpainting 模型比怎么样呢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月04日 17:37 |
| 收件人 | mayuelala/FollowYourCanvas ***@***.***> |
| 抄送人 | ustczhouyu ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [mayuelala/FollowYourCanvas] 请问模型可以做图像的outpainting吗？效果如何？ (Issue #1) |

感谢关注，是可以的，图像的outpainting可以当做是单帧的video进行操作

**Comment by mayuelala** [comment]
你可以参考下issue ，在import 最后加入一行 #2
