### ISSUE TITLE
loading model to cuda failded. Segmentation fauld (core dumped)

### ISSUE THREAD

**Issue by Tord-Zhang** [mayuelala/FollowYourCanvas#2]
When loading model to cuda, Segmentation fault is given. Any solution?

**Comment by ustczhouyu** [comment]
> When loading model to cuda, Segmentation fault is given. Any solution?

the same error!!!

**Comment by mayuelala** [comment]
which GPU are you using？

**Comment by jinqiupeter** [comment]
No models had been loaded to GPU when the error happened (checked via nvtop)

**Comment by yuzhongruicn** [comment]
same error here

**Comment by jinqiupeter** [comment]
Make sure your torch version matches the one in requirements.txt

**Comment by yuzhongruicn** [comment]
> Make sure your torch version matches the one in requirements.txt

Thanks for the reply! Did you solve it? I have checked that my torch version is identical to the requirements.txt, but still get this issue.

**Comment by tliby** [comment]
same error +1

**Comment by DataAIPlayer** [comment]
`from decord import VideoReader`
Put this line of code at the end to import

**Comment by mayuelala** [comment]
Segmentation fauld (core dumped) is not the final bug，you can from decord import VideoReader
Put this line of code at the end to import
